[CRIMAP-715] Remove BaseDecorator in favour of BasePresenter
ministryofjustice/laa-apply-for-criminal-legal-aid pull request #533
Opened 2023-11-08 16:40 UTC by MohammedHassanLatif

## Description of change
Refactored code changed from BaseDecorator to BasePresenter. Removed other decorator code and files.

## Link to relevant ticket
https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-715

## Notes for reviewer

## Screenshots of changes (if applicable)

### Before changes:

### After changes:

## How to manually test the feature

2023-11-08 17:18 UTC, willmcb commented on app/decorators/address_form_decorator.rb
> +class AddressFormDecorator < BasePresenter
Why not make this a `AddressFormPresenter` as well that way we aren't mixing concepts

2023-11-08 17:19 UTC, willmcb commented on app/presenters/crime_application_presenter.rb
> +    return unless applicant?
Is this a boy scout style addition unrelated to the general refactor you're doing here in relation to removing the concept of Decorators?

2023-11-08 17:20 UTC, willmcb requested changes
Few minor things to think about - looks good though happy to merge once they have been looked at / we have had a chat.

2023-11-09 17:29 UTC, hiboabd approved these changes
Looks good to me! 👏

2023-11-10 09:22 UTC, willmcb commented on app/presenters/crime_application_presenter.rb
> +    return unless applicant?
This can be removed / put back to its orignal state

2023-11-10 09:25 UTC, willmcb approved these changes
Looks good :)

2023-11-10 09:34 UTC, merged